version: '3.3'

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /home/ubuntu/sukhilLearn/promtail-config.yml:/etc/promtail/config.yml
      - ~/.pm2/logs:/root/.pm2/logs
    command: -config.file=/etc/promtail/config.yml

