version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=travelmemory
    ports:
      - "27017:27017"
    networks:
      - mongo_network
    restart: always
    volumes:
      - ./init-travelmemory.js:/docker-entrypoint-initdb.d/init-travelmemory.js

  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb_exporter
    environment:
      - MONGODB_URI=mongodb://root:admin123@mongodb:27017/travelmemory?authSource=admin
    ports:
      - "9216:9216"
    depends_on:
      - mongodb
    networks:
      - mongo_network
    restart: always

networks:
  mongo_network:
    driver: bridge

